config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: "homes#top"
get "/home/about" => "homes#about", as: "about"
resources :books,only: [:new, :create, :index, :show, :edit, :update, :destroy] do
 resources :book_comments, only: [:create, :destroy]
 resource :favorites, only: [:create, :destroy]
 end
resources :users,only: [:index,:show, :edit, :update] do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
end
get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200 }
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, uniqueness: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :books, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower
has_one_attached :profile_image

validates :name, uniqueness: true
validates :name, length: { minimum: 2, maximum: 20 }
validates :introduction, length: {maximum: 50 }

def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
   @book = Book.find(params[:book_id])
   book_comment = @book.book_comments.find(params[:id])
   book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id)
    flash[:notice] = "You have updated book successfully."
   else
    render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @favorite_book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @favorite_book.id)
    favorite.save
  end

  def destroy
    @favorite_book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @favorite_book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end
  
  def about

  end  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 def create
     current_user.follow(params[:user_id])
     redirect_to request.referer
 end

 def destroy
     current_user.unfollow(params[:user_id])
     redirect_to request.referer
 end

 def followings
     user = User.find(params[:user_id])
     @users = user.followings
 end

 def followers
    user = User.find(params[:user_id])
    @users = user.followers
 end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@users = User.search_for(@content, @method)
		else
			@books = Book.search_for(@content, @method)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @users = User.all
  @book = Book.new
  @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully"
     redirect_to user_path(@user.id)
   else
    render :edit
   end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<div class="new_comment">
 <%= form_with(model:[book, book_comment], local: false) do |f| %>
 <div class="form-group">
 <%= f.text_area :comment, rows:"5", class:"form-control" %>
 </div>
 <div class="form-group">
 <%= f.submit "送信", class:"btn btn-success" %>
 </div>
 <% end %>
 </div>

app/views/book_comments/_index.html.erb
 <% book.book_comments.each do |book_comment| %>
 <tr>
  <td>
  <%= link_to user_path(book_comment.user_id) do %>
  <%= image_tag book_comment.user.get_profile_image(40,40) %><br>
  <%= book_comment.user.name %>
  <% end %>
  </td>
  <td>
  <%= book_comment.comment %>
  </td>
  <td>
   <% if book_comment.user == current_user %>
   <%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %>
  <% end %>
  </td>
 </tr>
 <% end %>
 

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %> <br>
<%= f.submit 'Update Book', class: "button btn btn-secondary" %>
 <% end %>
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>
 </div>
 </div>
 </div>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
     <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    <div class="row">
    <%= render 'users/list', user: current_user, book: @book %>
    </div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td><%= link_to user_path(book.user.id) do %>
  　　<%= image_tag book.user.get_profile_image(40,40) %>
 　　 　 <% end %>
      </td>
      <td>
      <%= link_to book_path(book.id) do %>
      <%= book.title %>
      <% end %>
      </td>
      <td>
      <%= book.body %>
      </td>
      <td id="favorite_buttons_<%= book.id %>">
      <%= render "favorites/btn", book: book %>
      </td>
      <td class="comments-count">コメント数: <%= book.book_comments.count %>
      </td>
    </tr>
    <% end %>
</tbody>
</table>
</div>
</div>
</div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
   <%= render 'users/list', user: @user, book: @new_book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
  <tbody>
  <tr id="book_<%= @book.id %>">
   <td>
    <%= link_to user_path(@book.user.id) do %>
    <%= image_tag @book.user.get_profile_image(40,40) %> <br>
    <%= @book.user.name %>
    <% end %>
   </td>
   <td>
    <%= link_to book_path(@book) do %>
    <%= @book.title %>
    <% end %>
   </td>
   <td>
    <%= @book.body %>
   </td>
   <td id="favorite_buttons_<%= @book.id %>">
     <%= render "favorites/btn", book: @book %>
   </td>
   <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
   <td>
    <% if @book.user == current_user %>
    <%= link_to "Edit", edit_book_path(@book.id), class: "button btn btn-success" %>
    <% end %>
   </td>
   <td>
    <% if @book.user == current_user %>
    <%= link_to book_path(@book.id), method: :delete, data: {confirm: "本当に消しますか？"} do %>
    <i class= "button btn btn-danger">Destroy</i>
    <% end %>
    <% end %>
   </td>
  </tr>
</tbody>
</table>
<table>
<table class="book_comments">
 <%= render 'book_comments/index', book: @book %>
</table>
　<%=form_with model:[@book,@book_comment], local: false do |f| %>
  <%= f.text_area :comment, size:"90x5" %>
  <%= f.submit '送信'%>
  <% end %>
</div>
</div>
</div>
</main>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= book.favorites.count %>
      <% end %>
      <% else %>
       <%= link_to book_favorites_path(book), method: :post, remote: true do %>
       <i class="fas fa-heart" aria-hidden="true"></i>
      <%= book.favorites.count %>
      <% end %>
     <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @favorite_book.id %>').html("<%= j(render "favorites/btn", book: @favorite_book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @favorite_book.id %>').html("<%= j(render "favorites/btn", book: @favorite_book) %>");

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
    <div class=row>
      <h1 class="px-3 mx-auto">welcome to<i class="fas fa-book"></i>
  <strong>Bookers!</strong></h1>
  </div>
  </div>

app/views/homes/top.html.erb
  <div class="container">
    <div class=row>
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to<i class="fas fa-book"></i>
        <strong>Bookers!!</strong></h1>
        <p>In<i class="fas fa-book"></i>
        <strong>Bookers,</strong></p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
          </div>
          </div>
       </div>
  </div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
     <td><%= image_tag user.get_profile_image(100,100) %></td>
     <td><%= user.name %></td>
     <td>フォロー数: <%= user.followings.count %></td>
     <td>フォロワー数: <%= user.followers.count %></td>
     <td>
      <% if current_user != user %>
      <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
      <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
      <% end %>
     </td>
     <td><%= link_to "Show", user_path(user) %></td>
   </tr>
   <% end %>
  </tbody>
</table>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
     <td><%= image_tag user.get_profile_image(100,100) %></td>
     <td><%= user.name %></td>
     <td>フォロー数: <%= user.followings.count %></td>
     <td>フォロワー数: <%= user.followers.count %></td>
     <td>
      <% if current_user != user %>
      <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
      <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
      <% end %>
     </td>
     <td><%= link_to "Show", user_path(user) %></td>
   </tr>
   <% end %>
  </tbody>
</table>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
 　 <% if @model == 'user' %>
 　 <h3>Users search for "<%= @content %>"</h3>
    <tbody>
      <tr>
      <th>image</th>
      <th>name</th>
    </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% elsif @model == 'book' %>
  <h3>Books search for "<%= @content %>"</h3>
    <tbody>
       <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
    </tr>
      <% @books.each do |book| %>
        <tr>
          <td>
           <%= link_to user_path(book.user.id) do %>
           <%= image_tag book.user.get_profile_image(40,40) %> <br>
           <%= book.user.name %>
           <% end %>
          </td>
          <td>
            <%= link_to book_path(book) do %>
            <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/_list.html.erb
 <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(63,63) %>
      <table class="table">
        <thead>
          <tr>
            <th>name</th>
            <td><%= user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= user.introduction %></td>
          </tr>
          <tr>
            <th>follows</th>
            <td>
              <%= link_to user_followings_path(user.id) do %>
              <%= user.followings.count %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>follwers</th>
            <td>
              <%= link_to user_followers_path(user.id) do %>
              <%= user.followers.count %>
              <% end %>
            </td>
          </tr>
      </table>
        <div class= "row">
          <p>
      <% if current_user != user %>
      <% if current_user.following?(user) %>
      <%= link_to user_relationships_path(user.id), method: :delete do %>
      <i class= "btn btn-success">フォロー外す</i>
      <% end %>
      <% else %>
      <%= link_to user_relationships_path(user.id), method: :post do %>
      <i class= "btn btn-success">フォローする</i>
      <% end %>
      <% end %>
      <% end %>
        </p>
        <% if current_user == user %>
        <%= link_to edit_user_path(user.id) do %>
        <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
        <% end %>
        <% end %>
        </div>
   <h2>New book</h2>
   <diV>
   <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class:"btn btn-success" %>
    </div>
  <% end %>
</diV>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"Name"%>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, class:"form-control", placeholder:"Introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-secondary"%>
        </div>
      <% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
    <%= render 'list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
 <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
     <td><%= image_tag user.get_profile_image(100,100) %></td>
     <td><%= user.name %></td>
     <td><%= link_to "Show", user_path(user) %></td>
   </tr>
   <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
   <%= render 'list', user: @user, book: @book %>
     </div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td><%= link_to user_path(book.user.id) do %>
  　　<%= image_tag book.user.get_profile_image(40,40) %>
 　　　 <% end %>
  </td>
      <td><%= link_to book_path(book.id) do %>
      <%= book.title %>
      <% end %>
      </td>
      <td><%= book.body %>
      </td>
      <td>
      </td>
    </tr>
    <% end %>
</tbody>
</table>
</div>
</div>
</div>
</main>