config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: "homes#top"
get "/home/about" => "homes#about", as: "about"
resources :books,only: [:new, :create, :index, :show, :edit, :update, :destroy] do
 resources :book_comments, only: [:create, :destroy]
 resource :favorites, only: [:create, :destroy]
 end
resources :users,only: [:index,:show, :edit, :update] do
  resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
end
get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200 }
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, uniqueness: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :books, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower
has_one_attached :profile_image

validates :name, uniqueness: true
validates :name, length: { minimum: 2, maximum: 20 }
validates :introduction, length: {maximum: 50 }

def follow(user_id)
  relationships.create(followed_id: user_id)
end

def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end

def following?(user)
  followings.include?(user)
end
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id)
    flash[:notice] = "You have updated book successfully."
   else
    render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @favorite_book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @favorite_book.id)
    favorite.save
  end

  def destroy
    @favorite_book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @favorite_book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end
  
  def about

  end  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

 before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@users = User.search_for(@content, @method)
		else
			@books = Book.search_for(@content, @method)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @users = User.all
  @book = Book.new
  @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully"
     redirect_to user_path(@user.id)
   else
    render :edit
   end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li>
         <%= link_to user_path(current_user), class: 'text-light' do %>
       <i class= 'fas fa-home text-light'></i>
        Home
        <% end %>
      </li>
      <li>
      <%= link_to users_path, class: 'text-light' do %>
          <i class="fas fa-users tekt-light"></i>
          Users
      <% end %>
      </li>
      <li>
       <%= link_to books_path, class: 'text-light' do %>
          <i class= 'fas fa-book-open text-light'></i>
          Books
       <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'text-light' do %>
        <i class= 'fas fa-sign-out-alt text_light'></i>
        Log out
        <% end %>
     </li>
      <% else %>
      <li>
        <%= link_to root_path, class: 'text-light' do %>
          <i class= 'fas fa-home text-light'></i>
          Home
        <% end %>
      </li>
      <li>
        <%= link_to about_path, class: 'text-light' do %>
          <i class= 'fas fa-link text-light'></i>
          About
        <% end %>
      </li>
      <li>
      <%= link_to new_user_registration_path, class: 'text-light' do %>
      <i class= 'fas fa-user-plus text-light'></i>
        Sign up
        <% end %>
      </li>
       <%= link_to new_user_session_path, class: 'text-light' do %>
       <i class= 'fas fa-sign-in-alt text-light'></i>
         Log in
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
    </nav>
    <div class=row>
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <%= render 'searches/form' %>
    </div>
  </div>
  </header>
<main>
  <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>
   <%= yield %>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
    <div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
      </div>
      </div>
    </div>
</footer>
  </body>
</html>